name: Debug
on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:
jobs:
  poll:
    runs-on: ubuntu-latest
    container: ghcr.io/fcobackup/fco-backup-fetcher:main
    steps:
      - name: Run chrome
        run: sudo -u seluser xvfb-run /opt/google/chrome/chrome
